import Header from './components/Header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import restaurantData from '../../restaurantData.json'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header title={restaurantData.restaurant.name}>
        </Header>
        {children}
        </body>
    </html>
  )
}
